<?php
header('Content-Type: text/javascript; charset=utf8');
header('Access-Control-Allow-Origin: http://www2.warwick.ac.uk/');
header('Access-Control-Max-Age: 3628800');
header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE');

require_once('config.php');
require_once('class/userdetails.inc.php');

$json = array();
$callback = '';
if(isset($_GET['callback'])) 	$callback = filter_var($_GET['callback'], FILTER_SANITIZE_STRING);
if(isset($_GET['id'])) 			$id 		= filter_var($_GET['id'], FILTER_SANITIZE_STRING);
if(isset($_GET['d'])) 			$decision	= filter_var($_GET['d'], FILTER_SANITIZE_STRING);

if(isset($id) && isset($decision)) {
	
	// ***
	// Current user details
	// *
	
	$userDetails 	= new userDetails();
	$myDetails		= $userDetails->getArray();
	$getAuthorise	= $userDetails->getAuthorise();
	
	
	if(!$myDetails['is_supervisor'] && !$myDetails['is_admin']) exit; // Exit if not an supervirsor or admin
	
	// Check the ID received is ok
	
	$authorised = false;
	$authorised_record = array();
	foreach($getAuthorise as $authorise) if($authorise['id'] == $id) {
		$authorised = true;
		$authorised_record = $authorise;
	}

	if($authorised == true) {
		$leave_period = '';
		if($authorised_record['allDay'] == '1') {
			$start = substr($authorised_record['start'],0,10);
			$end = substr($authorised_record['end'],0,10);
			$leave_period = 'annual leave booked '.($start == $end ? 'on '.$start : 'from '.$start.' to '.$end );
		} else {
			$leave_period = 'annual leave booked from '.$authorised_record['start'].' to '.$authorised_record['end'];
		}

		if($decision == 1) {
			mysql_update('events', $id, array('auth' => '1', 'authoriser' => '\''.$myDetails['user'].'\''));
			
			$subject = 'Annual Leave System - Leave Accepted';
			$message = "The $leave_period has been accepted."."\r\n\r\nThis is an automatic email generated by the Annual Leave System";
		} else {
			mysql_query("DELETE FROM events WHERE id = '$id' AND area_id = '".AREA."' LIMIT 1");
			
			$subject = 'Annual Leave System - Leave Declined';
			$message = "The $leave_period has been declined."."\r\n\r\nThis is an automatic email generated by the Annual Leave System";
		}
		
		$headers = 'From: noreply@warwick.ac.uk' . "\r\n" .
			'Reply-To: noreply@warwick.ac.uk' . "\r\n" .
			'X-Mailer: PHP/' . phpversion();
		
		mail($authorised_record['email'], $subject, $message, $headers);
	}

	echo $callback.'('.json_encode($authorised).');';
}
?>